### ISSUE TITLE
figure out wallet re-import problem

### ISSUE THREAD

**Issue by hortonelectric** [BitLox/bitlox-copay#4]
watch only wallets should be able to be re-imported from BWS server, but can't..let's  figure it.

**Comment by hideoussquid** [comment]
Check the code for "wallet import" (separate from create, featured on the original onboarding and current new wallet screen. This "import" is specifically designed for wallets that have already existed on the bws instance.

**Comment by BitLox** [comment]
Has been fixed, create first then if error import.
