### ISSUE TITLE
why are 2 addresses listed in the receive addresses section in copay wallet when I first add a newly created wallet

### ISSUE THREAD

**Issue by hortonelectric** [BitLox/bitlox-copay#7]

**Comment by BitLox** [comment]
You mean like a double entry of a transaction?

**Comment by hortonelectric** [comment]
No.. i mean when you import a new wallet from your bitlox for the first
time. Then go to the wallet in copay and click receive. Then navigate to
address list. There are two addresses listed.

I don't have any empirical proof of this theory but i think the first
address is the master public key for the xpub. The second listed address
matches what's on the bitlox screen

On Apr 5, 2017 7:24 PM, "BitLox" <notifications@github.com> wrote:

You mean like a double entry of a transaction?

Sent from my iPhone

> On 5 Apr 2017, at 19:04, hortonelectric <notifications@github.com> wrote:
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/BitLox/bitlox-copay/issues/7#issuecomment-291831857>,
or mute the thread

**Comment by BitLox** [comment]
Ok I wondered what that rogue address was. That should be suppressed.

**Comment by hortonelectric** [comment]
This is a non-issue. There are two addresses because one got used.
